// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCqT-fuLU6PBlMBLeXbCzV6JnWGaKB8RiE',
    appId: '1:298686459109:web:e4da82b95bf338a96df80c',
    messagingSenderId: '298686459109',
    projectId: 'jydaclean-73f00',
    authDomain: 'jydaclean-73f00.firebaseapp.com',
    storageBucket: 'jydaclean-73f00.firebasestorage.app',
    measurementId: 'G-K86NYWBCNV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCubYiG55IJM3JWAcfCeb6IG5y_ZJDtHCw',
    appId: '1:298686459109:android:8035f6a22765a4476df80c',
    messagingSenderId: '298686459109',
    projectId: 'jydaclean-73f00',
    storageBucket: 'jydaclean-73f00.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD0aXHCtLHY-QMMtTlC5_J8BdqkKkH1_fI',
    appId: '1:298686459109:ios:94abb39fb38659aa6df80c',
    messagingSenderId: '298686459109',
    projectId: 'jydaclean-73f00',
    storageBucket: 'jydaclean-73f00.firebasestorage.app',
    iosBundleId: 'com.example.jydaclean',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD0aXHCtLHY-QMMtTlC5_J8BdqkKkH1_fI',
    appId: '1:298686459109:ios:94abb39fb38659aa6df80c',
    messagingSenderId: '298686459109',
    projectId: 'jydaclean-73f00',
    storageBucket: 'jydaclean-73f00.firebasestorage.app',
    iosBundleId: 'com.example.jydaclean',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCqT-fuLU6PBlMBLeXbCzV6JnWGaKB8RiE',
    appId: '1:298686459109:web:f027ec1a46563af36df80c',
    messagingSenderId: '298686459109',
    projectId: 'jydaclean-73f00',
    authDomain: 'jydaclean-73f00.firebaseapp.com',
    storageBucket: 'jydaclean-73f00.firebasestorage.app',
    measurementId: 'G-8GTEBE20KM',
  );
}
